### ISSUE TITLE
Alguns aparelhos não cadastram expansor

### ISSUE THREAD

**Issue by Pablo-Jean** [padotec/padotec.bug.report#13]
Intermitente ( O erro/bug ocorre de vez em quando )

### Essa Issue está impedindo alguma funcionalidade ?

 Sim, alguns aparelhos não conseguem cadastrar o expansor.

### Qual a data e horário que o bug ocorreu ?

1 de Junho de 2022, 11:30

### Faça uma descrição detalhada do problema que você está enfrentando:

Ao adiconar um expansor, é enviado o primeiro comando de _SET_KEY_, mas o app nao recebe resposta. Causando falha na operação

### Quais são os etapas para reproduzir o erro/bug ?

Cadastrar o expansor em qualquer aparelho.

### Você pode nos providenciar algum log/print do erro?

Não consegui tirar print :(

**Comment by hbfcarlos** [comment]
Resolvido.  Era ajuste no pacote relacionado a outras alterações.
