### ISSUE TITLE
Mal funcionamento, Reset e Restauração de fechadura

### ISSUE THREAD

**Issue by lsclaudino-hw** [padotec/padotec.bug.report#14]
- [ ] Transiente ( O erro/bug ocorreu uma vez )
- [x] Intermitente ( O erro/bug ocorre de vez em quando )
- [ ] Permanente (O erro/bug ocorre repetidas vezes)

Essa Issue está impedindo alguma funcionalidade ?
- [x] Sim
- [ ] Não

Qual a data e horário que o bug ocorreu ?  
> R:  01/06/2022, 11:50

Faça uma descrição detalhada do problema que você está enfrentando:  
> R: Ao cadastrar manualmente vários códigos na fechadura (após 6 códigos cadastrados), a fechadura entra em estado indefinido (responde a teclas, mas nenhum comando é executado).
Após alguns segundos a fechadura é resetada (watchdog). Depois de algumas vezes feito o mesmo procedimento, a fechadura fez sozinha a restauração para modo de fábrica.

Quais são os etapas para reproduzir o erro/bug ?  
> R:  Entrar no menu de códigos e cadastrar seguidamente vários códigos

Você pode nos providenciar algum log/print do erro?  
> R: Não.

**Comment by Pablo-Jean** [comment]
O problema ocorre quando uma senha que ja existe é cadastrada.
