### ISSUE TITLE
Dados de horário de acesso cíclico não aparecem na eKey

### ISSUE THREAD

**Issue by Pablo-Jean** [padotec/padotec.bug.report#20]
- [x] Sempre

## Essa Issue está impedindo alguma funcionalidade ?
Não

Qual a data e horário que o bug ocorreu ?
21/06/2022 @ 09:30

## Faça uma descrição detalhada do problema que você está enfrentando:

Ao checar as informações de uma Ekey previamente cadastrada, as informações de horário cíclicas não são carregadas com os valores configurados, quando a Ekey possui horário inicial e final (cíclico).

## Quais são os etapas para reproduzir o erro/bug ?

- Cadastrar uma Ekey cíclica com horário inicial e final definidos. 
- Voltar ao menu de Ekey
- Voltar a Ekey que foi cadastrada e checar que as informações não estão presentes

## Você pode nos providenciar algum log/print do erro?

Claro!

![WhatsApp Image 2022-06-21 at 09 39 55](https://user-images.githubusercontent.com/74741351/174802375-d5114fc1-2c3d-4f4d-8dc9-5f71ce8f41ce.jpeg)

**Comment by hbfcarlos** [comment]
Done
