### ISSUE TITLE
Usuário com nomes trocados na adição de E-key

### ISSUE THREAD

**Issue by gabrielfonte** [padotec/padotec.bug.report#3]
Qual o Tipo de Issue ?
[ ] Transiente ( O erro/bug ocorreu uma vez )
[ ] Intermitente ( O erro/bug ocorre de vez em quando )
[X] Permanente (O erro/bug ocorre repetidas vezes)

Essa Issue está impedindo alguma funcionalidade ?
[] Sim
[X] Não

Qual a data e horário que o bug ocorreu ?
> R: 11:17 31/05/2022

Faça uma descrição detalhada do problema que você está enfrentando:
> Nos logs gerados na adição de E-key, os nomes do usuário que adicionou e o usuário adicionado estão invertidos. Verifiquei na database para ver se os valores estavam corretos e aparentemente o problema está no app pois o UserName e o targetUser estão corretos.

Quais são os etapas para reproduzir o erro/bug ?
> Adicionar uma e-key de usuário pelo App e aguardar receber o log

![79910e98-b5b2-4d86-bd14-8b1505c83cf8](https://user-images.githubusercontent.com/32528442/171206088-cb48080c-cc8d-4317-be0e-11af0ba4e06a.jpg)

**Comment by hbfcarlos** [comment]
Ajustado.
