### ISSUE TITLE
Gateway não envia resposta pra Alexa

### ISSUE THREAD

**Issue by gabrielfonte** [padotec/padotec.bug.report#8]
Alexa não envia resposta para o servidor após acionamento.

Qual o Tipo de Issue ?
- [ ]  Transiente ( O erro/bug ocorreu uma vez )
- [ ]  Intermitente ( O erro/bug ocorre de vez em quando )
- [x]  Permanente (O erro/bug ocorre repetidas vezes)

Essa Issue está impedindo alguma funcionalidade ?
- [x]  Sim
- [ ]  Não

Qual a data e horário que o bug ocorreu ?
R: 13:59 31/05/2022

Faça uma descrição detalhada do problema que você está enfrentando:
R: Ao enviar comandos pela Alexa, o gateway não envia a resposta de volta para o backend.

Quais são os etapas para reproduzir o erro/bug ?
R: Operar a fechadura pela Alexa.

**Comment by gabrielfonte** [comment]
Para o commando de vínculo também ocorreu o mesmo problema, um exemplo de JSON:

 {
        "sender":       "4bf4be63-fbe6-4d2a-bfbf-ed9aeae4dbbd",
        "recipient":    "13b2b0c8-c911-435e-b53d-1093aa774da1",
        "messageId":    0,
        "payload":      {
                "command":      128,
                "status":       200
        }
}

**Comment by hbfcarlos** [comment]
Fixed para o comando **messageId**
